### ISSUE TITLE
Ignore whitespace at start of line

### ISSUE THREAD

**Issue by kovasap** [fannheyward/coc-lines#36]
I've noticed that when writing python, the line completion only works if i start my typing at the start of a line (no tabs or spaces before my cursor).  Interestingly, the line completion will show me lines that do start with tabs/spaces!  Is there a way to set it so that the completion will work even if there are tabs/spaces before my cursor in the line?  Ideally, it would work even if there are any characters before my cursor.

Thanks!

**Comment by fannheyward** [comment]
Added `coc.source.lines.startOfLineOnly`, true as default. You can set it to false for your case.

**Comment by kovasap** [comment]
I have this line in my vimrc, but it doesn't seem to enable this feature:
```
let g:coc_user_config.source = {'lines': {'startOfLineOnly': 'false'}}
```
Is this what you mean by setting the value to false?  I also tried `v:false` and `0`.

**Comment by fannheyward** [comment]
```
let g:coc_user_config = {                      
          \'coc.source.lines.startOfLineOnly': v:false
          \}
```

**Comment by kovasap** [comment]
Perfect, that works!  Thank you!
